# Generated by Django 5.2.1 on 2025-05-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('passwort', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('priorityImg', models.TextField(default='./assets/img/vector_strich.svg')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('color', models.CharField(blank=True, max_length=20)),
                ('initial', models.CharField(blank=True, max_length=2)),
                ('is_selected', models.BooleanField(default=False)),
                ('assigned_guests', models.ManyToManyField(blank=True, related_name='tasks', to='join_app.guestcontact')),
                ('subtasks', models.ManyToManyField(blank=True, to='join_app.subtask')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='tasks', to='join_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='guestcontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_contacts', to='join_app.user'),
        ),
    ]
