# Generated by Django 5.2.1 on 2025-05-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcontact',
            name='user',
        ),
    ]
