# Generated by Django 5.2.1 on 2025-05-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_remove_guestcontact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_guests',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_users',
        ),
    ]
