# Generated by Django 5.2.1 on 2025-05-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_remove_task_assigned_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.ManyToManyField(blank=True, related_name='guest_contacts', to='join_app.guestcontact'),
        ),
    ]
