# Generated by Django 5.2.1 on 2025-05-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_guests',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='join_app.guestcontact'),
        ),
    ]
