# Generated by Django 5.2.1 on 2025-05-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_task_assigned_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
