# Generated by Django 5.2.1 on 2025-05-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0006_remove_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
        migrations.RemoveField(
            model_name='task',
            name='initial',
        ),
    ]
