# Generated by Django 5.2.1 on 2025-05-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0007_remove_task_color_remove_task_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwort',
            new_name='password',
        ),
    ]
