# Generated by Django 5.2.1 on 2025-05-28 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0010_alter_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='join_app.task'),
        ),
    ]
