# Generated by Django 5.2.1 on 2025-05-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0011_subtask_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_app.task'),
        ),
    ]
