# Generated by Django 5.2.1 on 2025-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0012_remove_subtask_task_id_remove_task_subtasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtask_ids_cache',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
