# Generated by Django 5.2.1 on 2025-05-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0013_task_subtask_ids_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask_ids_cache',
        ),
    ]
