# Generated by Django 5.2.1 on 2025-06-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0018_usercontact_alter_task_assigned_user_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContact',
            new_name='User',
        ),
    ]
