# Generated by Django 5.2.1 on 2025-06-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0019_rename_usercontact_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserContact',
        ),
    ]
