# Generated by Django 5.2.1 on 2025-06-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0020_rename_user_usercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
