# Generated by Django 5.2.1 on 2025-06-11 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0021_alter_usercontact_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='password',
        ),
        migrations.AddField(
            model_name='usercontact',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
