# Generated by Django 5.2.1 on 2025-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0022_remove_usercontact_email_remove_usercontact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
