# Generated by Django 5.2.1 on 2025-06-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0023_usercontact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='name',
        ),
    ]
