# Generated by Django 5.2.1 on 2025-06-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0025_usercontact_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='plain_password',
        ),
    ]
