# Generated by Django 5.2.1 on 2025-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0026_remove_usercontact_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='user',
        ),
        migrations.AddField(
            model_name='usercontact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
