# Generated by Django 5.2.1 on 2025-06-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0027_remove_usercontact_user_usercontact_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContact',
            new_name='User',
        ),
    ]
