# Generated by Django 5.2.1 on 2025-06-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0028_rename_usercontact_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
