# Generated by Django 5.2.1 on 2025-06-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0032_userprofile_alter_task_assigned_user'),
        ('user_auth_app', '0004_remove_userprofile_bio_remove_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='user_auth_app.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
